### ISSUE TITLE
可否发个搭建教程

### ISSUE THREAD

**Issue by Creator2K** [WsureDev/warframe-info-api#4]
不太懂咋搭建诶，希望大佬发个教程可以自己搭建使用

**Comment by WsureDev** [comment]
这个就是个普通的npm项目，你只需要下载安装nodejs，yarn
然后git clone本项目
接着在项目目录打开命令行，输入 yarn -i 或者 npm install 就可以安装依赖了
最后只需要yarn run start 或者 npm run start 就好了

**Comment by Guocaiqi** [comment]
我在宝塔面板成功运行了，但是不能像大佬的演示地址那样操作，运行日记里也看见成功了。
proxy设置为true 映射的7890端口
请问怎样才能像演示网址一样能够直接访问呢
