### ISSUE TITLE
平原系时间的指示不准确

### ISSUE THREAD

**Issue by GamerNoTitle** [WsureDev/warframe-info-api#6]
就例如说希图斯已经到早上了，从https://api.warframestat.us/pc/cetusCycle 获取的是`*h *min *s to night`，但是从本项目获取的是`已过去 *min *s 到 早上`这样的回复，而不是显示还有多久到晚上

**Comment by WsureDev** [comment]
这种情况会出现在昼夜交替之后的几分钟之内（wf世界状态的数据来自于de官方api，经过warframestat格式化，如果你仔细观察，游戏内其实偶尔也会出现已过去xxx的描述），第二种情况是上游[https://api.warframestat.us](https://api.warframestat.us/pc/cetusCycle)挂掉之后，在上游api恢复之前都是用`已过去`来表示。我会观察`已过去`状态的滞后情况，如果严重的话，会提高从上游api刷新缓存的频率
